apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-app
type: Opaque
data:
  mysql-root-password: U2VjdXJlUGFzczEyMyE=    # SecurePass123! (base64 encoded)
  mysql-database: ZGI=                         # db (base64 encoded)
  mysql-username: YWRtaW4=                     # admin (base64 encoded)
  mysql-password: U2VjdXJlUGFzczEyMyE=         # SecurePass123! (base64 encoded)